// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gcmrec_fit
List gcmrec_fit(double s, IntegerVector k, NumericVector tau, NumericVector caltimes, NumericVector gaptimes, NumericVector censored, NumericVector intercepts, NumericVector slopes, NumericVector lastperrep, NumericVector effagebegin, NumericVector effage, NumericMatrix cov, NumericVector offset, double alpha_seed, NumericVector beta_seed, NumericVector z, int rho_type, double tol, int maxit);
RcppExport SEXP _gcmrec_gcmrec_fit(SEXP sSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP offsetSEXP, SEXP alpha_seedSEXP, SEXP beta_seedSEXP, SEXP zSEXP, SEXP rho_typeSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov(covSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_seed(alpha_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_seed(beta_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(gcmrec_fit(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, z, rho_type, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// gcmrec_baseline
List gcmrec_baseline(double s, IntegerVector k, NumericVector tau, NumericVector caltimes, NumericVector gaptimes, NumericVector censored, NumericVector intercepts, NumericVector slopes, NumericVector lastperrep, NumericVector effagebegin, NumericVector effage, NumericMatrix cov, NumericVector offset, NumericVector diseff, double alpha, NumericVector beta, NumericVector z, int rho_type);
RcppExport SEXP _gcmrec_gcmrec_baseline(SEXP sSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP offsetSEXP, SEXP diseffSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP zSEXP, SEXP rho_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov(covSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(gcmrec_baseline(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha, beta, z, rho_type));
    return rcpp_result_gen;
END_RCPP
}
// gcmrec_frailty_fit
List gcmrec_frailty_fit(double s, IntegerVector k, NumericVector tau, NumericVector caltimes, NumericVector gaptimes, NumericVector censored, NumericVector intercepts, NumericVector slopes, NumericVector lastperrep, NumericVector effagebegin, NumericVector effage, NumericMatrix cov, NumericVector offset, NumericVector diseff, double alpha_seed, NumericVector beta_seed, double xi_seed, NumericVector z, int rho_type, double tol, int maxit, int xi_method);
RcppExport SEXP _gcmrec_gcmrec_frailty_fit(SEXP sSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP offsetSEXP, SEXP diseffSEXP, SEXP alpha_seedSEXP, SEXP beta_seedSEXP, SEXP xi_seedSEXP, SEXP zSEXP, SEXP rho_typeSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP xi_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov(covSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_seed(alpha_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_seed(beta_seedSEXP);
    Rcpp::traits::input_parameter< double >::type xi_seed(xi_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type xi_method(xi_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(gcmrec_frailty_fit(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, z, rho_type, tol, maxit, xi_method));
    return rcpp_result_gen;
END_RCPP
}
// gcmrec_jackknife
NumericMatrix gcmrec_jackknife(double s, IntegerVector k, NumericVector tau, NumericVector caltimes, NumericVector gaptimes, NumericVector censored, NumericVector intercepts, NumericVector slopes, NumericVector lastperrep, NumericVector effagebegin, NumericVector effage, NumericMatrix cov, NumericVector offset, double alpha_seed, NumericVector beta_seed, int rho_type, double tol, int maxit, int nthreads);
RcppExport SEXP _gcmrec_gcmrec_jackknife(SEXP sSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP offsetSEXP, SEXP alpha_seedSEXP, SEXP beta_seedSEXP, SEXP rho_typeSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov(covSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_seed(alpha_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_seed(beta_seedSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gcmrec_jackknife(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, rho_type, tol, maxit, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// gcmrec_jackknife_frailty
NumericMatrix gcmrec_jackknife_frailty(double s, IntegerVector k, NumericVector tau, NumericVector caltimes, NumericVector gaptimes, NumericVector censored, NumericVector intercepts, NumericVector slopes, NumericVector lastperrep, NumericVector effagebegin, NumericVector effage, NumericMatrix cov, NumericVector offset, NumericVector diseff, double alpha_seed, NumericVector beta_seed, double xi_seed, int rho_type, double tol, int maxit, int xi_method, int nthreads);
RcppExport SEXP _gcmrec_gcmrec_jackknife_frailty(SEXP sSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP caltimesSEXP, SEXP gaptimesSEXP, SEXP censoredSEXP, SEXP interceptsSEXP, SEXP slopesSEXP, SEXP lastperrepSEXP, SEXP effagebeginSEXP, SEXP effageSEXP, SEXP covSEXP, SEXP offsetSEXP, SEXP diseffSEXP, SEXP alpha_seedSEXP, SEXP beta_seedSEXP, SEXP xi_seedSEXP, SEXP rho_typeSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP xi_methodSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type caltimes(caltimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gaptimes(gaptimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastperrep(lastperrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effagebegin(effagebeginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effage(effageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov(covSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diseff(diseffSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_seed(alpha_seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_seed(beta_seedSEXP);
    Rcpp::traits::input_parameter< double >::type xi_seed(xi_seedSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type xi_method(xi_methodSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gcmrec_jackknife_frailty(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, rho_type, tol, maxit, xi_method, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gcmrec_gcmrec_fit", (DL_FUNC) &_gcmrec_gcmrec_fit, 19},
    {"_gcmrec_gcmrec_baseline", (DL_FUNC) &_gcmrec_gcmrec_baseline, 18},
    {"_gcmrec_gcmrec_frailty_fit", (DL_FUNC) &_gcmrec_gcmrec_frailty_fit, 22},
    {"_gcmrec_gcmrec_jackknife", (DL_FUNC) &_gcmrec_gcmrec_jackknife, 19},
    {"_gcmrec_gcmrec_jackknife_frailty", (DL_FUNC) &_gcmrec_gcmrec_jackknife_frailty, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_gcmrec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
