# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gcmrec_fit <- function(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, z, rho_type, tol, maxit) {
    .Call(`_gcmrec_gcmrec_fit`, s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, z, rho_type, tol, maxit)
}

.gcmrec_baseline <- function(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha, beta, z, rho_type) {
    .Call(`_gcmrec_gcmrec_baseline`, s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha, beta, z, rho_type)
}

.gcmrec_frailty_fit <- function(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, z, rho_type, tol, maxit, xi_method) {
    .Call(`_gcmrec_gcmrec_frailty_fit`, s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, z, rho_type, tol, maxit, xi_method)
}

.gcmrec_jackknife <- function(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, rho_type, tol, maxit, nthreads) {
    .Call(`_gcmrec_gcmrec_jackknife`, s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, alpha_seed, beta_seed, rho_type, tol, maxit, nthreads)
}

.gcmrec_jackknife_frailty <- function(s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, rho_type, tol, maxit, xi_method, nthreads) {
    .Call(`_gcmrec_gcmrec_jackknife_frailty`, s, k, tau, caltimes, gaptimes, censored, intercepts, slopes, lastperrep, effagebegin, effage, cov, offset, diseff, alpha_seed, beta_seed, xi_seed, rho_type, tol, maxit, xi_method, nthreads)
}

